# Generated by Django 3.0.7 on 2020-08-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=70)),
                ('tz', models.CharField(max_length=80)),
                ('members', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='app.duplicate')),
            ],
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default='')),
                ('end_time', models.DateTimeField(default='')),
                ('user_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='app.user')),
            ],
        ),
    ]
